### PR TITLE
feat: return mutation as object that does not need to be reparsed

### PR DESCRIPTION
**Pull request by Taepper**
See https://github.com/loculus-project/loculus/pull/1446

### CODE REVIEW

**Comment by fengelniederhammer** [comment]
I was about to bring up that discussion anyway, I really like the change :+1: 

In LAPIS we will most probably keep the old `mutation` field for backwards compatibility and convenience. Do we want to do the same here? Or do we rather want to strip the redundant data from the SILO responses?

**Comment by Taepper** [comment]
That is a good point, just returning both might be viable. What do you think @chaoran-chen. Keeping both fields only in LAPIS or also in SILO?

**Comment by fengelniederhammer** [comment]
(Also just to keep in mind: this PR should not be merged without preparation in LAPIS if it still contains breaking changes.)

**Comment by Taepper** [comment]
Similar to https://github.com/GenSpectrum/LAPIS/issues/710 it might be better to include both in SILO, then we can order by all fields that are also returned by LAPIS

**Comment by Taepper** [comment]
Should be ready to merge now, as it is non-breaking for LAPIS

**Comment by Taepper** [comment]
Some QOL changes introduced to query.test.js, where the actual result is directly written to a file that can be easier compared and copied

**Pull request merged**
