### PR TITLE
Setup Dependency Management

### LINKED ISSUE #10: Setup Dependency Management
Probably we will go for https://conan.io/.

### PR DESCRIPTION
**Pull request by JonasKellerer**
Resolves #10

### CODE REVIEW

**Comment by JonasKellerer** [comment]
We decided to use Docker for release and CI. Conan is now optional, for local development (to use IDE features).

**Review by fengelniederhammer — APPROVED** [review]

**Review by chaoran-chen — COMMENTED** [review]
I'm getting the following error message on mac:

<details>
<summary>
Error log
</summary>

```
boost/1.80.0: Applying build-requirement: b2/4.9.3
Downloading conan_sources.tgz completed [5.58k]
Decompressing conan_sources.tgz completed [0.00k]
boost/1.80.0: Configuring sources in /Users/chachen/.conan/data/boost/1.80.0/_/_/source/src
Downloading boost_1_80_0.tar.bz2 completed [113154.20k]                                  boost/1.80.0: /1.80.0:
boost/1.80.0:
boost/1.80.0: Apply patch (conan): Fails the build when there is no iconv backend
boost/1.80.0: Apply patch (conan): Fails the build when mpi is not configured
boost/1.80.0: Apply patch (official): Directory iterators may fail to construct for a network share on Windows prior to 10
boost/1.80.0: Apply patch (official): On Windows, weakly_canonical fails to process paths that start with the "\\?\" prefix
boost/1.80.0: Apply patch (official): Containers are not in a valid state after moving
boost/1.80.0: Apply patch (official): On POSIX systems that don't support *at APIs, compilation fails due to a missing include
boost/1.80.0: Building your package in /Users/chachen/.conan/data/boost/1.80.0/_/_/build/5dd2575ae3d9ae8680b1ff4040bd2440f98c9551
boost/1.80.0: Generator txt created conanbuildinfo.txt
boost/1.80.0: Calling generate()
boost/1.80.0: Aggregating env generators
boost/1.80.0: Calling build()
boost/1.80.0: WARN: replace_in_file didn't find pattern '/* thread_local */' in '/Users/chachen/.conan/data/boost/1.80.0/_/_/source/src/boost/stacktrace/detail/libbacktrace_impls.hpp' file.
boost/1.80.0: WARN: replace_in_file didn't find pattern '/* static __thread */' in '/Users/chachen/.conan/data/boost/1.80.0/_/_/source/src/boost/stacktrace/detail/libbacktrace_impls.hpp' file.
boost/1.80.0: WARN: replace_in_file didn't find pattern 'local generic-os = [ set.difference $(all-os) : aix darwin vxworks solaris osf hpux ] ;' in '/Users/chachen/.conan/data/boost/1.80.0/_/_/source/src/tools/build/src/tools/gcc.jam' file.
boost/1.80.0: WARN: replace_in_file didn't find pattern 'local no-threading = android beos haiku sgi darwin vxworks ;' in '/Users/chachen/.conan/data/boost/1.80.0/_/_/source/src/tools/build/src/tools/gcc.jam' file.
boost/1.80.0: WARN: Patching user-config.jam
boost/1.80.0: WARN: Using the new toolchains and generators without specifying a build profile (e.g: -pr:b=default) is discouraged and might cause failures and unexpected behavior
boost/1.80.0: WARN:
using zlib : 1.2.13 : <include>"/Users/chachen/.conan/data/zlib/1.2.13/_/_/package/c9f99894de7cd0d22d0bdedcf23221ef3d5c6f04/include" <search>"/Users/chachen/.conan/data/zlib/1.2.13/_/_/package/c9f99894de7cd0d22d0bdedcf23221ef3d5c6f04/lib" <name>z ;
using bzip2 : 1.0.8 : <include>"/Users/chachen/.conan/data/bzip2/1.0.8/_/_/package/ac48fbe81a58f9445f80c07076de04c18aef1ced/include" <search>"/Users/chachen/.conan/data/bzip2/1.0.8/_/_/package/ac48fbe81a58f9445f80c07076de04c18aef1ced/lib" <name>bz2 ;
using lzma : 5.4.0 : <include>"/Users/chachen/.conan/data/xz_utils/5.4.0/_/_/package/c9f99894de7cd0d22d0bdedcf23221ef3d5c6f04/include" <search>"/Users/chachen/.conan/data/xz_utils/5.4.0/_/_/package/c9f99894de7cd0d22d0bdedcf23221ef3d5c6f04/lib" <name>lzma ;
using "gcc" :  :  "/usr/bin/g++" :
 ;
boost/1.80.0: WARN: b2 -q target-os=linux architecture=x86 address-model=64 binary-format=elf abi=sysv --layout=system --user-config=/Users/chachen/.conan/data/boost/1.80.0/_/_/source/src/tools/build/user-config.jam -sNO_ZLIB=0 -sNO_BZIP2=0 -sNO_LZMA=0 -sNO_ZSTD=1 boost.locale.icu=off --disable-icu boost.locale.iconv=off --disable-iconv define=LZMA_API_STATIC threading=multi visibility=hidden link=static variant=release --with-iostreams --with-random --with-regex --with-serialization --with-system toolset=gcc define=_GLIBCXX_USE_CXX11_ABI=1 pch=on linkflags="" cxxflags="-fPIC" install --prefix=/Users/chachen/.conan/data/boost/1.80.0/_/_/package/5dd2575ae3d9ae8680b1ff4040bd2440f98c9551 -j8 --abbreviate-paths -d0 --debug-configuration --build-dir="/Users/chachen/.conan/data/boost/1.80.0/_/_/build/5dd2575ae3d9ae8680b1ff4040bd2440f98c9551/build-release"
/bin/sh: /Users/chachen/.conan/data/b2/4.9.3/_/_/package/4db1be536558d833e52e862fd84d64d75c2b3656/bin/b2: cannot execute binary file
boost/1.80.0:
boost/1.80.0: ERROR: Package '5dd2575ae3d9ae8680b1ff4040bd2440f98c9551' build failed
boost/1.80.0: WARN: Build folder /Users/chachen/.conan/data/boost/1.80.0/_/_/build/5dd2575ae3d9ae8680b1ff4040bd2440f98c9551/build-release
ERROR: boost/1.80.0: Error in build() method, line 880
	self.run(full_command)
	ConanException: Error 126 while executing b2 -q target-os=linux architecture=x86 address-model=64 binary-format=elf abi=sysv --layout=system --user-config=/Users/chachen/.conan/data/boost/1.80.0/_/_/source/src/tools/build/user-config.jam -sNO_ZLIB=0 -sNO_BZIP2=0 -sNO_LZMA=0 -sNO_ZSTD=1 boost.locale.icu=off --disable-icu boost.locale.iconv=off --disable-iconv define=LZMA_API_STATIC threading=multi visibility=hidden link=static variant=release --with-iostreams --with-random --with-regex --with-serialization --with-system toolset=gcc define=_GLIBCXX_USE_CXX11_ABI=1 pch=on linkflags="" cxxflags="-fPIC" install --prefix=/Users/chachen/.conan/data/boost/1.80.0/_/_/package/5dd2575ae3d9ae8680b1ff4040bd2440f98c9551 -j8 --abbreviate-paths -d0 --debug-configuration --build-dir="/Users/chachen/.conan/data/boost/1.80.0/_/_/build/5dd2575ae3d9ae8680b1ff4040bd2440f98c9551/build-release"
```
</details>

The last line contains `target-os=linux` which seems a bit weird?

But it's great that it works on Linux. You can already merge it if you want and we can debug mac another time.

**Comment by chaoran-chen** [comment]
@JonasKellerer, changing `conanprofile` as suggested in the README was very helpful and got me closer. Now, I'm getting this error message:

```
[  5%] Building CXX object CMakeFiles/siloapi.dir/src/silo.cpp.o
/Users/chachen/Documents/repos/GenSpectrum/LAPIS-SILO/src/silo.cpp:7:10: fatal error: 'syncstream' file not found
#include <syncstream>
         ^~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/siloapi.dir/src/silo.cpp.o] Error 1
make[1]: *** [CMakeFiles/siloapi.dir/all] Error 2
make: *** [all] Error 2
```

My GCC version in case it's relevant:

```
➜  LAPIS-SILO git:(conanNotInCmake) gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.27)
Target: x86_64-apple-darwin22.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by chaoran-chen** [comment]
As @Taepper explained to me, `syncstream` is just not supported by Apple Clang (https://en.cppreference.com/w/cpp/compiler_support#C.2B.2B20_library_features). I.e., if we want to allow compiling with Apple Clang, we have to avoid using `syncstream`.

This is obviously not a problem of the dependency management / build setup :)

**Pull request merged**
