### PR TITLE
doc: add documentation for the lineage_definitions format

### PR DESCRIPTION
**Pull request by Taepper**
### Summary

Add documentation for the lineage definitions file, which is required for the specification of monophyletic sublineage queries.

## PR Checklist

- [X] All necessary documentation has been adapted or there is an issue to do so.
- [X] The implemented feature is covered by an appropriate test.

### CODE REVIEW

**Comment by fengelniederhammer** [comment]
Linking https://github.com/GenSpectrum/LAPIS/issues/978 for reference.

**Comment by Taepper** [comment]
I wanted something that is at least one step above "ah, I found an example in the codebase" which is what happened now for Loculus ^^

**Review by fengelniederhammer — APPROVED** [review]
I agree, this is definitely better than nothing. I don't want to block here, we can improve it later.

**Comment by Taepper** [comment]
Ok, fixed a type and will merge

**Pull request merged**
