### PR TITLE
ci: add workflow that comments changelog preview on PRs

### PR DESCRIPTION
**Pull request by fengelniederhammer**
## PR Checklist

- ~~[ ] All necessary documentation has been adapted or there is an issue to do so.~~
- ~~[ ] The implemented feature is covered by an appropriate test.~~

### CODE REVIEW

**Comment by fengelniederhammer** [comment]
See https://github.com/GenSpectrum/LAPIS/pull/840 for a similar PR that has a current change that causes a comment.

**Comment by Taepper** [comment]
Shouldn't this already comment that preview on this PR?

**Comment by fengelniederhammer** [comment]
> Shouldn't this already comment that preview on this PR?

There are currently no changes that would trigger a version bump (that's also why there is currently no open version PR in SILO)

**Comment by Taepper** [comment]
Ah, I thought this was meant to show, what the change log would look like *after* the current PR is merged

**Comment by fengelniederhammer** [comment]
> Ah, I thought this was meant to show, what the change log would look like _after_ the current PR is merged

Exactly, that's what it does. But this PR doesn't introduce any relevant changes. Maybe the `feat` in the PR title confused you, I'll remove it - it's a leftover from me testing it.

**Comment by Taepper** [comment]
Ah, yes that is precisely it! Thanks!

**Review by Taepper — APPROVED** [review]

**Pull request merged**
