### PR TITLE
Runtime Config

### PR DESCRIPTION
**Pull request by Taepper**
feat: tidying up CLI and file configuration for runtime config. Added option for specifying the port

### Summary

The port on which SILO listens to requests should be able to be specified.

Furthermore, I edited the way the configs are parsed such that there is a default `RuntimeConfig` (default constructor), which has 2 member functions for overwriting its values from 1. the config file and 2. the CLI arguments

## PR Checklist

- [x] All necessary documentation has been adapted or there is an issue to do so.
- [x] The implemented feature is covered by an appropriate test.

### CODE REVIEW

**Review by fengelniederhammer — COMMENTED** [review]
Maybe we should also document somewhere (in the README) that the runtime config exists? I just noticed that this is not mentioned there.

**Comment by Taepper** [comment]
> Maybe we should also document somewhere (in the README) that the runtime config exists? I just noticed that this is not mentioned there.

Yes, I will do so! What is with the StartUp Config. Would you have any objections if I merge all the information from that into the RuntimeConfig?

**Comment by Taepper** [comment]
Then we have one config for --api and one config for --preprocessing. I would also change the way the preprocessing config currently works, to be consistent with this. Therefore, we consistently have

`default configuration values < config file < CLI arguments`

Cornelius and Christian both mentioned that environment variables should be added to those lists. Do you object to have that between config and CLI for the final precendences:

`default configuration values < config file < environment variables < CLI arguments`

**Comment by pflanze** [comment]
Commit 70523298b0cbb513f703e567bd9db9281d29f871 works for me, and the code looked good to me. Documentation will be good. I don't think it needs any tests at this time in the project's history since the CI and my test runner will exercise the important options already.

**Review by pflanze — APPROVED** [review]
LGTM, and works for SILO_PORT.

**Pull request merged**
